# Generated by Django 4.2.7 on 2025-09-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, help_text='UUID from Riigikogu API', max_length=36, unique=True)),
                ('name', models.CharField(help_text='Fraktsiooni nimi', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faction',
                'verbose_name_plural': 'Factions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, help_text='UUID from Riigikogu API', max_length=36, unique=True)),
                ('first_name', models.CharField(help_text='Eesnimi', max_length=100)),
                ('last_name', models.CharField(help_text='Perekonnanimi', max_length=100)),
                ('full_name', models.CharField(help_text='Täisnimi', max_length=200)),
                ('active', models.BooleanField(default=True, help_text='Aktiivne liige')),
                ('email', models.EmailField(blank=True, help_text='E-mail', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Telefon', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, help_text='Sugu', max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Sünni kuupäev', null=True)),
                ('parliament_seniority', models.IntegerField(blank=True, help_text='Staaž parlamendis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Politician',
                'verbose_name_plural': 'Politicians',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PlenarySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.IntegerField(help_text='Riigikogu koosseisu number')),
                ('plenary_session', models.IntegerField(help_text='Istungjärgu number')),
                ('date', models.DateTimeField(help_text='Istungi alguseaeg')),
                ('title', models.TextField(help_text='Istungi pealkiri')),
                ('edited', models.BooleanField(default=False, help_text='Kas stenogramm on toimetatud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plenary Session',
                'verbose_name_plural': 'Plenary Sessions',
                'ordering': ['-date'],
                'unique_together': {('membership', 'plenary_session', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, help_text='Päevakorrapunkti UUID', max_length=36, unique=True)),
                ('date', models.DateTimeField(help_text='Päevakorrapunkti aeg')),
                ('title', models.TextField(help_text='Päevakorrapunkti pealkiri')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plenary_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='parliament_speeches.plenarysession')),
            ],
            options={
                'verbose_name': 'Agenda Item',
                'verbose_name_plural': 'Agenda Items',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, help_text='Sündmuse UUID', max_length=36, unique=True)),
                ('event_type', models.CharField(choices=[('SPEECH', 'Speech'), ('VOTING_RESULT', 'Voting Result'), ('PRESENCE_CHECK', 'Presence Check'), ('SESSION_END', 'Session End')], default='SPEECH', help_text='Sündmuse tüüp', max_length=20)),
                ('date', models.DateTimeField(help_text='Sündmuse aeg')),
                ('speaker', models.CharField(help_text='Kõneleja nimi', max_length=200)),
                ('text', models.TextField(help_text='Kõne või sõnavõtu tekst')),
                ('link', models.URLField(blank=True, help_text='Link stenogrammile', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='parliament_speeches.agendaitem')),
                ('politician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='parliament_speeches.politician')),
            ],
            options={
                'verbose_name': 'Speech',
                'verbose_name_plural': 'Speeches',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='parliament__date_37fc26_idx'), models.Index(fields=['speaker'], name='parliament__speaker_0b935c_idx'), models.Index(fields=['event_type'], name='parliament__event_t_6fd99f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PoliticianFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, help_text='Liikmelisuse algus', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Liikmelisuse lõpp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='parliament_speeches.faction')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_memberships', to='parliament_speeches.politician')),
            ],
            options={
                'verbose_name': 'Politician Faction Membership',
                'verbose_name_plural': 'Politician Faction Memberships',
                'unique_together': {('politician', 'faction', 'start_date')},
            },
        ),
    ]
