# Generated by Django 4.2.7 on 2025-09-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0002_clean_html_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI kokkuvõte kõnest', null=True),
        ),
    ]
