# Generated by Django 4.2.7 on 2025-09-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0004_add_ai_summary_to_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='total_time_seconds',
            field=models.IntegerField(blank=True, help_text='Kogu päevakorrapunkti kestus sekundites', null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='total_time_seconds',
            field=models.IntegerField(blank=True, help_text='Kogu kõneaeg sekundites', null=True),
        ),
    ]
