# Generated by Django 4.2.7 on 2025-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0005_add_total_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='photo',
            field=models.ImageField(blank=True, help_text='Poliitiku foto', null=True, upload_to='politicians/photos/'),
        ),
        migrations.AddField(
            model_name='politician',
            name='photo_big',
            field=models.ImageField(blank=True, help_text='Poliitiku suur foto', null=True, upload_to='politicians/photos_big/'),
        ),
        migrations.AddField(
            model_name='politician',
            name='photo_extension',
            field=models.CharField(blank=True, help_text='Foto faililaiend API-st', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='photo_filename',
            field=models.CharField(blank=True, help_text='Foto failinimi API-st', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='photo_uuid',
            field=models.CharField(blank=True, help_text='Foto UUID API-st', max_length=36, null=True),
        ),
    ]
