# Generated by Django 4.2.7 on 2025-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0006_add_politician_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='ai_summary_en',
            field=models.TextField(blank=True, help_text='AI kokkuvõte päevakorrapunktist inglise keeles', null=True),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='ai_summary_ru',
            field=models.TextField(blank=True, help_text='AI kokkuvõte päevakorrapunktist vene keeles', null=True),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='title_en',
            field=models.TextField(blank=True, help_text='Päevakorrapunkti pealkiri inglise keeles', null=True),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='title_ru',
            field=models.TextField(blank=True, help_text='Päevakorrapunkti pealkiri vene keeles', null=True),
        ),
        migrations.AddField(
            model_name='plenarysession',
            name='title_en',
            field=models.TextField(blank=True, help_text='Istungi pealkiri inglise keeles', null=True),
        ),
        migrations.AddField(
            model_name='plenarysession',
            name='title_ru',
            field=models.TextField(blank=True, help_text='Istungi pealkiri vene keeles', null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='ai_summary_en',
            field=models.TextField(blank=True, help_text='AI kokkuvõte kõnest inglise keeles', null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='ai_summary_ru',
            field=models.TextField(blank=True, help_text='AI kokkuvõte kõnest vene keeles', null=True),
        ),
    ]
