# Generated by Django 4.2.7 on 2025-09-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0007_add_multilingual_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianProfileComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('POLITICAL_POSITION', 'Political Position'), ('TOPIC_EXPERTISE', 'Topic Expertise'), ('RHETORICAL_STYLE', 'Rhetorical Style'), ('ACTIVITY_PATTERNS', 'Activity Patterns'), ('OPPOSITION_STANCE', 'Opposition Stance'), ('COLLABORATION_STYLE', 'Collaboration Style'), ('REGIONAL_FOCUS', 'Regional Focus'), ('ECONOMIC_VIEWS', 'Economic Views'), ('SOCIAL_ISSUES', 'Social Issues'), ('LEGISLATIVE_FOCUS', 'Legislative Focus')], help_text='Võrdluse kategooria', max_length=50)),
                ('comparison_et', models.TextField(help_text='Võrdlev analüüs eesti keeles')),
                ('comparison_en', models.TextField(blank=True, help_text='Võrdlev analüüs inglise keeles', null=True)),
                ('comparison_ru', models.TextField(blank=True, help_text='Võrdlev analüüs vene keeles', null=True)),
                ('similarity_score', models.IntegerField(default=0, help_text='Sarnasus skoor 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('politician_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_a', to='parliament_speeches.politician')),
                ('politician_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_b', to='parliament_speeches.politician')),
            ],
            options={
                'verbose_name': 'Politician Profile Comparison',
                'verbose_name_plural': 'Politician Profile Comparisons',
                'unique_together': {('politician_a', 'politician_b', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PoliticianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('POLITICAL_POSITION', 'Political Position'), ('TOPIC_EXPERTISE', 'Topic Expertise'), ('RHETORICAL_STYLE', 'Rhetorical Style'), ('ACTIVITY_PATTERNS', 'Activity Patterns'), ('OPPOSITION_STANCE', 'Opposition Stance'), ('COLLABORATION_STYLE', 'Collaboration Style'), ('REGIONAL_FOCUS', 'Regional Focus'), ('ECONOMIC_VIEWS', 'Economic Views'), ('SOCIAL_ISSUES', 'Social Issues'), ('LEGISLATIVE_FOCUS', 'Legislative Focus')], help_text='Profilieerimise kategooria', max_length=50)),
                ('analysis_et', models.TextField(help_text='AI analüüs eesti keeles')),
                ('analysis_en', models.TextField(blank=True, help_text='AI analüüs inglise keeles', null=True)),
                ('analysis_ru', models.TextField(blank=True, help_text='AI analüüs vene keeles', null=True)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Kvantitiivsed mõõdikud JSON formaadis')),
                ('confidence_score', models.IntegerField(default=0, help_text='AI kindluse skoor 0-100')),
                ('speeches_analyzed', models.IntegerField(default=0, help_text='Analüüsitud kõnede arv')),
                ('date_range_start', models.DateField(blank=True, help_text='Analüüsi perioodi algus', null=True)),
                ('date_range_end', models.DateField(blank=True, help_text='Analüüsi perioodi lõpp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='parliament_speeches.politician')),
            ],
            options={
                'verbose_name': 'Politician Profile',
                'verbose_name_plural': 'Politician Profiles',
                'ordering': ['politician', 'category'],
                'unique_together': {('politician', 'category')},
            },
        ),
    ]
