# Generated by Django 4.2.7 on 2025-09-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0008_politicianprofilecomparison_politicianprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianprofile',
            name='category',
            field=models.CharField(choices=[('POLITICAL_POSITION', 'Political Position'), ('TOPIC_EXPERTISE', 'Topic Expertise'), ('RHETORICAL_STYLE', 'Rhetorical Style'), ('ACTIVITY_PATTERNS', 'Activity Patterns'), ('OPPOSITION_STANCE', 'Opposition Stance'), ('COLLABORATION_STYLE', 'Collaboration Style'), ('REGIONAL_FOCUS', 'Regional Focus'), ('ECONOMIC_VIEWS', 'Economic Views'), ('SOCIAL_ISSUES', 'Social Issues'), ('LEGISLATIVE_FOCUS', 'Legislative Focus'), ('MEDIA_REACTIONS', 'Media Reactions')], help_text='Profilieerimise kategooria', max_length=50),
        ),
        migrations.AlterField(
            model_name='politicianprofilecomparison',
            name='category',
            field=models.CharField(choices=[('POLITICAL_POSITION', 'Political Position'), ('TOPIC_EXPERTISE', 'Topic Expertise'), ('RHETORICAL_STYLE', 'Rhetorical Style'), ('ACTIVITY_PATTERNS', 'Activity Patterns'), ('OPPOSITION_STANCE', 'Opposition Stance'), ('COLLABORATION_STYLE', 'Collaboration Style'), ('REGIONAL_FOCUS', 'Regional Focus'), ('ECONOMIC_VIEWS', 'Economic Views'), ('SOCIAL_ISSUES', 'Social Issues'), ('LEGISLATIVE_FOCUS', 'Legislative Focus'), ('MEDIA_REACTIONS', 'Media Reactions')], help_text='Võrdluse kategooria', max_length=50),
        ),
        migrations.CreateModel(
            name='MediaReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('POLITICAL_POSITION', 'Political Position'), ('TOPIC_EXPERTISE', 'Topic Expertise'), ('RHETORICAL_STYLE', 'Rhetorical Style'), ('ACTIVITY_PATTERNS', 'Activity Patterns'), ('OPPOSITION_STANCE', 'Opposition Stance'), ('COLLABORATION_STYLE', 'Collaboration Style'), ('REGIONAL_FOCUS', 'Regional Focus'), ('ECONOMIC_VIEWS', 'Economic Views'), ('SOCIAL_ISSUES', 'Social Issues'), ('LEGISLATIVE_FOCUS', 'Legislative Focus'), ('MEDIA_REACTIONS', 'Media Reactions')], help_text='Profilieerimise kategooria', max_length=50)),
                ('total_mentions', models.IntegerField(default=0, help_text='Kogu mainimiste arv meedias')),
                ('total_quotes', models.IntegerField(default=0, help_text='Kogu tsitaatide arv')),
                ('avg_sentiment', models.FloatField(default=0.0, help_text='Keskmine meeleolu (-1 kuni 1)')),
                ('media_analysis_et', models.TextField(help_text='Meedia analüüs eesti keeles')),
                ('media_analysis_en', models.TextField(blank=True, help_text='Meedia analüüs inglise keeles', null=True)),
                ('media_analysis_ru', models.TextField(blank=True, help_text='Meedia analüüs vene keeles', null=True)),
                ('media_summary_et', models.TextField(help_text='Lühike meedia kokkuvõte eesti keeles')),
                ('media_summary_en', models.TextField(blank=True, help_text='Lühike meedia kokkuvõte inglise keeles', null=True)),
                ('media_summary_ru', models.TextField(blank=True, help_text='Lühike meedia kokkuvõte vene keeles', null=True)),
                ('quotes_data', models.JSONField(blank=True, default=list, help_text='Tsitaadid JSON formaadis')),
                ('sources_data', models.JSONField(blank=True, default=list, help_text='Allikad JSON formaadis')),
                ('time_series_data', models.JSONField(blank=True, default=list, help_text='Ajaline andmestik JSON formaadis')),
                ('data_confidence', models.FloatField(default=0.0, help_text='Andmete usaldusväärsus (0-1)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_reactions', to='parliament_speeches.politician')),
            ],
            options={
                'verbose_name': 'Media Reaction',
                'verbose_name_plural': 'Media Reactions',
                'ordering': ['politician', 'category'],
                'unique_together': {('politician', 'category')},
            },
        ),
    ]
