# Generated by Django 4.2.7 on 2025-09-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0009_alter_politicianprofile_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(help_text='AI kokkuvõte päevakorrapunktist')),
                ('summary_text_en', models.TextField(blank=True, help_text='AI kokkuvõte inglise keeles', null=True)),
                ('summary_text_ru', models.TextField(blank=True, help_text='AI kokkuvõte vene keeles', null=True)),
                ('xml_response', models.TextField(blank=True, help_text='Täielik XML vastus dekrüpteeritud ID-dega', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_summary', to='parliament_speeches.agendaitem')),
            ],
            options={
                'verbose_name': 'Agenda Summary',
                'verbose_name_plural': 'Agenda Summaries',
            },
        ),
        migrations.CreateModel(
            name='AgendaDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_text', models.TextField(help_text='Otsuse kirjeldus')),
                ('decision_text_en', models.TextField(blank=True, help_text='Otsuse kirjeldus inglise keeles', null=True)),
                ('decision_text_ru', models.TextField(blank=True, help_text='Otsuse kirjeldus vene keeles', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='parliament_speeches.agendaitem')),
                ('politician', models.ForeignKey(blank=True, help_text='Poliitik kes tegi otsuse (null kui kollektiivne)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_decisions', to='parliament_speeches.politician')),
            ],
            options={
                'verbose_name': 'Agenda Decision',
                'verbose_name_plural': 'Agenda Decisions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgendaActivePolitician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_description', models.TextField(help_text='Aktiivsuse kirjeldus ja positsioon')),
                ('activity_description_en', models.TextField(blank=True, help_text='Aktiivsuse kirjeldus inglise keeles', null=True)),
                ('activity_description_ru', models.TextField(blank=True, help_text='Aktiivsuse kirjeldus vene keeles', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_politician', to='parliament_speeches.agendaitem')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_in_agendas', to='parliament_speeches.politician')),
            ],
            options={
                'verbose_name': 'Agenda Active Politician',
                'verbose_name_plural': 'Agenda Active Politicians',
            },
        ),
    ]
