# Generated by Django 4.2.7 on 2025-09-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0010_agendasummary_agendadecision_agendaactivepolitician'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianProfilePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('POLITICAL_POSITION', 'Political Position'), ('TOPIC_EXPERTISE', 'Topic Expertise'), ('RHETORICAL_STYLE', 'Rhetorical Style'), ('ACTIVITY_PATTERNS', 'Activity Patterns'), ('OPPOSITION_STANCE', 'Opposition Stance'), ('COLLABORATION_STYLE', 'Collaboration Style'), ('REGIONAL_FOCUS', 'Regional Focus'), ('ECONOMIC_VIEWS', 'Economic Views'), ('SOCIAL_ISSUES', 'Social Issues'), ('LEGISLATIVE_FOCUS', 'Legislative Focus')], help_text='Profilieerimise kategooria', max_length=50)),
                ('period_type', models.CharField(choices=[('AGENDA', 'Agenda Item'), ('PLENARY_SESSION', 'Plenary Session'), ('MONTH', 'Month'), ('YEAR', 'Year'), ('ALL', 'All Time')], help_text='Perioodi tüüp', max_length=20)),
                ('month', models.CharField(blank=True, help_text='Kuu formaadis MM.YYYY (kui period_type=MONTH)', max_length=7, null=True)),
                ('year', models.IntegerField(blank=True, help_text='Aasta (kui period_type=YEAR)', null=True)),
                ('analysis', models.TextField(help_text='AI analüüs eesti keeles')),
                ('analysis_en', models.TextField(blank=True, help_text='AI analüüs inglise keeles', null=True)),
                ('analysis_ru', models.TextField(blank=True, help_text='AI analüüs vene keeles', null=True)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Kvantitiivsed mõõdikud JSON formaadis')),
                ('confidence_score', models.IntegerField(default=0, help_text='AI kindluse skoor 0-100')),
                ('speeches_analyzed', models.IntegerField(default=0, help_text='Analüüsitud kõnede arv')),
                ('date_range_start', models.DateField(blank=True, help_text='Analüüsi perioodi algus', null=True)),
                ('date_range_end', models.DateField(blank=True, help_text='Analüüsi perioodi lõpp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.ForeignKey(blank=True, help_text='Päevakorrapunkt (kui period_type=AGENDA)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_parts', to='parliament_speeches.agendaitem')),
                ('plenary_session', models.ForeignKey(blank=True, help_text='Istung (kui period_type=PLENARY_SESSION)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_parts', to='parliament_speeches.plenarysession')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_parts', to='parliament_speeches.politician')),
            ],
            options={
                'verbose_name': 'Politician Profile Part',
                'verbose_name_plural': 'Politician Profile Parts',
                'ordering': ['politician', 'category', 'period_type'],
                'unique_together': {('politician', 'category', 'period_type', 'month'), ('politician', 'category', 'period_type', 'year'), ('politician', 'category', 'period_type', 'plenary_session'), ('politician', 'category', 'period_type', 'agenda_item')},
            },
        ),
    ]
