# Generated by Django 4.2.7 on 2025-09-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0011_politicianprofilepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Statistika nimi eesti keeles', max_length=200, unique=True)),
                ('name_ru', models.CharField(blank=True, help_text='Statistika nimi vene keeles', max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, help_text='Statistika nimi inglise keeles', max_length=200, null=True)),
                ('value', models.BigIntegerField(help_text='Statistika väärtus')),
                ('percentage', models.FloatField(blank=True, help_text='Protsent (kui rakendub)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistics Entry',
                'verbose_name_plural': 'Statistics Entries',
                'ordering': ['name'],
            },
        ),
    ]
