# Generated by Django 4.2.7 on 2025-09-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0012_add_statistics_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicianprofilepart',
            name='confidence_score',
        ),
    ]
