# Generated by Django 4.2.7 on 2025-09-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0013_remove_confidence_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediareaction',
            name='data_confidence',
        ),
        migrations.RemoveField(
            model_name='politicianprofile',
            name='confidence_score',
        ),
        migrations.AddField(
            model_name='politician',
            name='profiles_already_profiled',
            field=models.IntegerField(default=0, help_text='Juba profileeritud profiilide arv'),
        ),
        migrations.AddField(
            model_name='politician',
            name='profiles_required',
            field=models.IntegerField(default=0, help_text='Profiilide arv, mida on vaja'),
        ),
    ]
