# Generated by Django 4.2.7 on 2025-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0014_add_profiling_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL slug (e.g., 'about-us')", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Pealkiri eesti keeles', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Meta kirjeldus eesti keeles', max_length=300, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Võtmesõnad eesti keeles', max_length=500, null=True)),
                ('content', models.TextField(help_text='Sisu eesti keeles')),
                ('title_en', models.CharField(blank=True, help_text='Pealkiri inglise keeles', max_length=200, null=True)),
                ('meta_description_en', models.TextField(blank=True, help_text='Meta kirjeldus inglise keeles', max_length=300, null=True)),
                ('keywords_en', models.CharField(blank=True, help_text='Võtmesõnad inglise keeles', max_length=500, null=True)),
                ('content_en', models.TextField(blank=True, help_text='Sisu inglise keeles', null=True)),
                ('title_ru', models.CharField(blank=True, help_text='Pealkiri vene keeles', max_length=200, null=True)),
                ('meta_description_ru', models.TextField(blank=True, help_text='Meta kirjeldus vene keeles', max_length=300, null=True)),
                ('keywords_ru', models.CharField(blank=True, help_text='Võtmesõnad vene keeles', max_length=500, null=True)),
                ('content_ru', models.TextField(blank=True, help_text='Sisu vene keeles', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Kas lehekülg on avaldatud')),
                ('show_in_menu', models.BooleanField(default=False, help_text='Kas näidata menüüs')),
                ('menu_order', models.IntegerField(default=0, help_text='Järjekord menüüs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Text Page',
                'verbose_name_plural': 'Text Pages',
                'ordering': ['menu_order', 'title'],
            },
        ),
    ]
