# Generated by Django 4.2.7 on 2025-09-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0015_textpage'),
    ]

    operations = [
        # Remove obsolete PoliticianProfile model (replaced by PoliticianProfilePart)
        migrations.DeleteModel(
            name='PoliticianProfile',
        ),
        # Remove obsolete PoliticianProfileComparison model (not actively used)
        migrations.DeleteModel(
            name='PoliticianProfileComparison',
        ),
    ]
