# Generated by Django 4.2.7 on 2025-10-01 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0017_remove_old_ai_summary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaactivepolitician',
            name='politician',
            field=models.ForeignKey(blank=True, help_text='Aktiivne poliitik (null kui ei olnud eriti aktiivset)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_in_agendas', to='parliament_speeches.politician'),
        ),
        migrations.AlterField(
            model_name='mediareaction',
            name='category',
            field=models.CharField(choices=[('POLITICAL_POSITION', 'Political Position'), ('TOPIC_EXPERTISE', 'Topic Expertise'), ('RHETORICAL_STYLE', 'Rhetorical Style'), ('ACTIVITY_PATTERNS', 'Activity Patterns'), ('OPPOSITION_STANCE', 'Opposition Stance'), ('COLLABORATION_STYLE', 'Collaboration Style'), ('REGIONAL_FOCUS', 'Regional Focus'), ('ECONOMIC_VIEWS', 'Economic Views'), ('SOCIAL_ISSUES', 'Social Issues'), ('LEGISLATIVE_FOCUS', 'Legislative Focus')], help_text='Profilieerimise kategooria', max_length=50),
        ),
    ]
