# Generated by Django 4.2.7 on 2025-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0020_set_initial_generation_and_parsing_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentParseError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('API_CONNECTION', 'API Connection Error'), ('DATA_PARSING', 'Data Parsing Error'), ('MISSING_DATA', 'Missing Required Data'), ('VALIDATION', 'Data Validation Error'), ('DATABASE', 'Database Error'), ('PHOTO_DOWNLOAD', 'Photo Download Error'), ('OTHER', 'Other Error')], default='OTHER', help_text='Vea tüüp', max_length=50)),
                ('error_message', models.TextField(help_text='Veateade')),
                ('error_details', models.TextField(blank=True, help_text='Täiendavad detailid JSON formaadis', null=True)),
                ('entity_type', models.CharField(blank=True, help_text='Üksuse tüüp (politician, session, agenda, speech)', max_length=50, null=True)),
                ('entity_id', models.CharField(blank=True, help_text='Üksuse identifikaator (UUID või ID)', max_length=200, null=True)),
                ('entity_name', models.CharField(blank=True, help_text='Üksuse nimi või pealkiri', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Parliament Parse Error',
                'verbose_name_plural': 'Parliament Parse Errors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='parliament__created_6c2c09_idx'), models.Index(fields=['error_type'], name='parliament__error_t_554c9e_idx')],
            },
        ),
    ]
