# Generated by Django 4.2.7 on 2025-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0021_add_parliament_parse_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentparseerror',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, help_text='Aasta, millega see viga on seotud', null=True),
        ),
    ]
