# Generated by Django 4.2.7 on 2025-10-02 08:00

from django.db import migrations


def set_existing_errors_to_2025(apps, schema_editor):
    """Set year to 2025 for all existing parse errors without a year"""
    ParliamentParseError = apps.get_model('parliament_speeches', 'ParliamentParseError')
    
    # Update all records where year is NULL
    updated_count = ParliamentParseError.objects.filter(year__isnull=True).update(year=2025)
    
    if updated_count > 0:
        print(f"Updated {updated_count} parse error(s) to year 2025")


def reverse_migration(apps, schema_editor):
    """Reverse the migration by setting year back to NULL"""
    ParliamentParseError = apps.get_model('parliament_speeches', 'ParliamentParseError')
    
    # Set year back to NULL for records that were set to 2025
    ParliamentParseError.objects.filter(year=2025).update(year=None)


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_speeches', '0022_parliamentparseerror_year'),
    ]

    operations = [
        migrations.RunPython(set_existing_errors_to_2025, reverse_migration),
    ]
